### ISSUE TITLE
Extension installed yesterday, personalised, working ... then all gone overnight!

### ISSUE THREAD

**Issue by x333xxx** [umfana/FaviconBar#10]
Yesterday I installed the Favicon extension, personalised the content, got it all working satisfactorily and shut down my MacBook when I went to bed. This morning the bar has reset to the default settings, eg the New York Times is bookmarked and none of the bookmarks I'd entered and tested are shown.

Please advise!

**Comment by RoryCombe** [comment]
Sorry to hear that. Are you on OS X El Capitan and Safari 9? I haven't had much time to dedicate to testing the new updates.

**Comment by RoryCombe** [comment]
I've since tested on Safari 9 on Yosemite and it's maintaining my bookmarks in the settings

**Comment by popcornhax** [comment]
I realize this is an old request - I did have it crop up on my machine also when using multiple windows.  It's hard to pinpoint but I believe it will be addressed in the next version.

**Comment by popcornhax** [comment]
Since a lot has been rebuilt this should be addressed in the current version (1.3.1), so I believe this issue can be closed.
