### ISSUE TITLE
YouTube Favicons problems based on URLs?

### ISSUE THREAD

**Issue by neo-neo1** [umfana/FaviconBar#11]
I took a screenshot and will let the screenshot explain much more clearly. The proper YouTube favicon only appears during the homepage of YouTube. 

If I place a direct link to my YouTube subscriptions URL the favicon changes to the same favicon as my GMAIL favicon uses. For clarification, I also have a GMAIL favicon and it is the same exact favicon as the one the bottom image (the improper one). </br>
![favicon_error_yt](https://cloud.githubusercontent.com/assets/6996362/10685176/bcb71948-7924-11e5-8a45-4fe6298d4e6f.png)

**Comment by gregforcey** [comment]
I noticed a similar issue with Flickr. If I bookmark the flickr.com homepage the correct flickr favicon shows. But if I bookmark https://www.flickr.com/photos/friends/ then it shows the yahoo favicon not the flickr one.

**Comment by popcornhax** [comment]
The extension doesn't pull favicon in the "proper" way because that would require loading up all your pages each time a window is launched, so sometimes it gets wonky results.  Some additional smarts could probably be added in the future to help with this.

**Comment by neo-neo1** [comment]
@dbrowder I was hoping that the smarts needed would include a simple bug fix. Just save the favicon per the URL, not the domain. I assume loading it every time is not needed. 

But anyway, I have abandoned this add-on months ago unfortunately, still no viable replacement.

**Comment by popcornhax** [comment]
Just an update:  Getting correct/better favicons has been addressed for the next release and the current test code is pulling the correct Youtube/Flickr icons.  I am also planning to have custom favicon support in the next  release so any of the icons can be changed, but that has not been completed yet.  Soon.

**Comment by popcornhax** [comment]
This is included in the current release (1.3.1) so I believe this issue can be closed.
