### ISSUE TITLE
Change Focus to webpage after clicking icon in toolbar

### ISSUE THREAD

**Issue by gregforcey** [umfana/FaviconBar#12]
I noticed that when you click an icon in the favicon bar and the webpage loads, you can't use the page down key or spacebar key to scroll on the page. You have to click on the web page first, then the page down or spacebar key works. Is there any way to automatically change the focus to the webpage after the icon is clicked in favicon bar?

**Comment by popcornhax** [comment]
I realize this is an old request, but just an update:  This bug has been addressed and should be corrected in the next release.

**Comment by popcornhax** [comment]
This is included in the current release (1.3.1) so I believe this issue can be closed.
