### ISSUE TITLE
I can see most, but not all, of my bookmarks. How about...

### ISSUE THREAD

**Issue by 31r34Nn** [umfana/FaviconBar#13]
…letting us change the size of the icons, or scrolling so we can see all of our favorites at once. Or whatever you can do.

**Comment by 31r34Nn** [comment]
Does anyone have the same problem?

**Comment by popcornhax** [comment]
I agree, this can be fixed and wouldn't be too difficult.  I'm hoping I can find some time to hack away at this project a bit.

**Comment by popcornhax** [comment]
I realize this is an older request, but just wanted to update: The following additions have been made to address this - an option for smaller icons, and the ability to scroll the favicon bar left & right if icons go off the screen.  Scrolling is done with two-finger gestures on touchpad or right-left swipes on a magic mouse.  This should be released in the next version.

**Comment by popcornhax** [comment]
This has been released in the current version (1.3.1) so I believe this issue can be closed.
