### ISSUE TITLE
Is it possible to be able to place the favicon bar within the safari toolbar (instead of below)?

### ISSUE THREAD

**Issue by ghost** [umfana/FaviconBar#14]

**Comment by pfriesch** [comment]
No, since there is no API for this in Safari.

**Comment by Ryanrpm** [comment]
You could always put all of your bookmarks into the Favicon bar and then hide the Favorites bar...

That essentially does what you're asking for.

**Comment by RoryCombe** [comment]
@isn0gud is correct and @Ryanrpm's suggestion is the best I could offer too, so closing this issue

**Comment by Ryanrpm** [comment]
Love all the changes and additional options to customize. Thank you!

**Comment by RoryCombe** [comment]
All props to @dbrowder - it's his great work in the new version 👏
