### ISSUE TITLE
How do it remove favicon from the favicon bar

### ISSUE THREAD

**Issue by 517Design** [umfana/FaviconBar#15]
How do it remove favicon from the favicon bar? Tried right clicking but that doesn't work

**Comment by Ryanrpm** [comment]
Try this:
Go to Safari>Preferences>Extensions>Favicon Bar

All of your favicon links are separated by semicolons.  To remove one, delete it from that string.

**Comment by popcornhax** [comment]
I realize this is an older request, but just wanted to update: The addition of right-clicking to remove links has been added and should be in the next release.

**Comment by 517Design** [comment]
Awesome. I really like the bar. Will I be notified when the update comes out?

**Comment by popcornhax** [comment]
I will have to check with Rory, the original author about publishing to see about publishing and if the existing bars can be auto-updated.  I'm just about done with updates for this release, just finishing up some of the settings page and then bug fixes.  Either way, I will post a notice to these comments.

**Comment by popcornhax** [comment]
The current release (1.3.1) has right-click to delete and also delete from settings page so I think this issue can be considered closed.  It can be installed from this repository or it will update when Apple approves for the Safari Extension Gallery
