### ISSUE TITLE
We need a way to Change the Icon

### ISSUE THREAD

**Issue by JuJuBee22** [umfana/FaviconBar#17]
I really like this app, but some sites that I frequent often only get the default world icon, for instance f school websites and grade websites. Having about five of those doesn't make this easy to use because hovering over the icon does not show the link or main website name. Also, I frequent Google Drive, Gmail and my Google dashboard. Three Gs all the same is no better than the default world icon.  You already have "download image" and "copy image" on your right-click context menu, but no way to "paste image."
- Please allow a hover-over pop-up of the website name
- Please allow the ability to paste a different icon image over the default icon image.

Then.....you have an absolutely perfect app.

**Comment by Devon0227** [comment]
I fully agree with JuJuBee22's suggestions and would like to add the ability to drag icon to reorder items in the bar.

**Comment by popcornhax** [comment]
Agree with all of this.  It's all doable.  I'm just so happy to have found this extension and now I hope to help out where I can.

**Comment by Blazej-pl** [comment]
Custom favicon, sign me up! ;) 
Following @nevon lead waiting for good things to come.

**Comment by popcornhax** [comment]
I think this can be considered closed in the current release (1.3.1).  

You can change the icon to a custom image (not with right-click Paste, but via drag & drop or on the settings page).  Drag to reorder the bar is included.  Showing the title on hover is currently a can't-fix, for whatever reason Apple does not trigger hover events in Safari extensions - but you can see the title on right-click of an icon.
