### ISSUE TITLE
Favicons go missing?

### ISSUE THREAD

**Issue by Ryanrpm** [umfana/FaviconBar#18]
About 2 weeks ago, all my favicons went missing.  Only the default favicons are there.  Do they go away with a restart or something?   What makes them go away??   Tempted to go back to Apples normal bookmark bar if these just go away every so often...

Anyone else experiencing the same thing?

**Comment by popcornhax** [comment]
Do you mean the icons themselves go away and just look like question marks, or all of your custom bookmarks go away and just go back to the ones that come with the app?

**Comment by Ryanrpm** [comment]
Hi, thanks for getting back to me. 

It's the latter. The custom bookmarks go away and are replaced with the default bookmarks that come when you first install the Favicon extension.  However, I've only experienced this on our MacBook. My iMac seems to be fine and have had no issues.   Not sure if that helps?

Thanks,
Ryan

**Comment by popcornhax** [comment]
Thanks for the details.  I'm not the author of this, but I've decided to start working on it because I love the concept and want to knock out bugs and add some features.  Oddly enough, after asking about this the issue happened to me - so fixing it is top of my priority list.

**Comment by popcornhax** [comment]
Just an update, I think I have this fixed in the current codebase - so hopefully that will be ready for release within a few weeks.  I will update this post again when it is published.

**Comment by popcornhax** [comment]
With everything rebuilt this shouldn't happen anymore (in release 1.3.1), so I think this issue can be closed.
