### ISSUE TITLE
Yer breaking my heart here!

### ISSUE THREAD

**Issue by slashpots** [umfana/FaviconBar#19]
Mate this is the best idea for an extension I've seen in ages! But you went & crippled it with the clunky, ridiculously difficult method for adding links! I have the left side of my Chrome shortcut bar set up as a kind of Fav Bar, and I was stoked to see a proper one, but opening the pref pane and inserting csv text? Drag & drop would make it beautiful, even a list style URL entry bar (rather than a single line), would be a huge improvement, but this?
All the older folk I help would LOVE this (those who can still see a favicon I mean), but they'd never even attempt this, the first sign of a problem & they're gone!
And they are the ones who DO donate for things they like! But only if it works. I know this is not a big priority for you & you're probably telling me to go get .....  under your breath. Fair enough! Just HAD to let you know, good luck dude!

**Comment by popcornhax** [comment]
This can definitely be made better, and it looks like the author was working on it but didn't have time.  Hoping to help where I can, but no promises.

**Comment by popcornhax** [comment]
I think this can be considered completed with the current release, it has drag & drop, drag to add to bar, an add link button in the settings page and right-click menu.  Also an option for bigger favicon for those older folks :)

**Comment by slashpots** [comment]
Hi Rory, thanks for the reply, very much appreciated. Can't wait to go update FB and try it out. Best wishes for this & all you do in future mate, you understand how to do things the right way, not all that common these days. 
Thanks again ,
Michael (Lead illustrator for iBird Apps)

Sent from my iPhone 6s

Sunday, 12 February 2017, 4:16 AM +1000 from db  <notifications@github.com>:

**Comment by RoryCombe** [comment]
Thanks Michael (@slashpots). Credit should go to Dan @dbrowder as he made all the new additions possible. Hope you enjoy the new update.
