### ISSUE TITLE
Can't install in Safari 10.12.3

### ISSUE THREAD

**Issue by Blazej-pl** [umfana/FaviconBar#22]
Hi Rory & Dan,

I'm getting error attempting to install on Safari 10.0.3 (12602.4.8) on macOS Sierra 10.12.3:
An error occurred while installing the extension “Favicon Bar”.
Any advice how to get around it?

**Comment by popcornhax** [comment]
Unfortunately I'm seeing the same thing right now.  When version 1.2 is installed this error comes up, when uninstalled I can't even get 1.3 to install anymore even though I just did it successfully the other night.  I will keep looking into it.

**Comment by popcornhax** [comment]
Actually I think I have an idea of what's happening, but I won't be able to confirm it until I get home in a few hours.  I think that Safari won't let you install an "untrusted" extension on top of one that is published in the Extension Gallery.  We'd have to get this one published for the upgrade to work properly.

You could uninstall the version from the safari gallery and then install this version, but you would likely lose all of your links.

If you decide to do that, and it won't install, you would need to follow the instructions below as a workaround for installing downloaded extensions:

> To install a .safariextz file, go to:
> 
> System Preferences > Keyboard > Shortcuts > Keyboard (for OS X 10.11.4+)
> or
> 
> System Preferences > Keyboard > Shortcuts > Full Keyboard Access (for OS X 10.11.1 to 10.11.3)
> Then at the bottom of that dialog box, change the Full Keyboard Access:... option from Text boxes and lists only to All controls. You can then dismiss that System Preferences window.
> 
> Then, return to installing the extension. Double click your Safari Extension file and when the "Are you sure you want to install..." dialog box appears, do not click on the Trust button. Instead, use tab to select the Trust button and then confirm by hitting space. That should install the extension as required.

**I will confirm the above this evening and hopefully get things straightened out**

**Comment by Blazej-pl** [comment]
I was suspecting trust issue as well. No rush, I can wait for gallery update

**Comment by RoryCombe** [comment]
I just checked and I hadn't updated the manifest file to take into account the new version number. That's done now. @Blazej-pl can you update now?

**Comment by popcornhax** [comment]
Same situation with the updated manifest.  If FaviconBar 1.2 is installed via Safari extensions gallery then 1.3 cannot be installed from Github.

If 1.2 was installed manually via GitHub then 1.3 can bit installed via GitHub, but in the test I just did it didn't retain the links from 1.2... I'm not sure why yet.

I think for 1.3 to auto-update to those who installed from the Safari Extensions Gallery it has to be submitted and uploaded to apple.  The current version apple is serving is hosted on their servers: https://safari-extensions.apple.com/extensions/com.be.faviconbar-FHBT333DVL/FaviconBar.safariextz

@RoryCombe did you have to submit it when you built 1.2?  I've read that apple changed how the Safari Extension process works, but this is my first extension work.

**Comment by popcornhax** [comment]
Either way, I'm not 100% confident that the links from 1.2 will transfer over to 1.3 even though they should, so I would recommend backing them up before upgrading.  Will keep testing.

**Comment by Blazej-pl** [comment]
I've removed 1.2 and installed 1.3 by choosing "trust" and I'm using it. It blew me away, how much my Safari is better now! Take that, Apple :P I absolutely love it! 
![favicons_1 3](https://cloud.githubusercontent.com/assets/25329994/22730098/d1cdcde0-ede5-11e6-9215-5798159e9eda.png)

I've added more links by editing settings file, but uploading it makes no difference. Double checked for errors, but I'm not seeing one. Below my link file: [my fav bar 1.3 settings](https://www.dropbox.com/s/ofwzssu5tu53clj/Untitled.rtf?dl=0)
It would help to add "add link" button, so users don't have mess with the settings. 
Keep it up!

**Comment by popcornhax** [comment]
I can't say I intended for users to edit the settings file, it's more for backup or transferring to another Mac.   It would be possible to edit, but still not intended :)

If you right-click (or control+click) a blank area of the bar you will get a  Add Link menu option.  So that is a way to manually add links outside of drag & drop.  Having this on the settings page would be a good idea that I can add in the future.

**Comment by Blazej-pl** [comment]
right click, why didn't I think of that? Right, it's invisible ;)
I've spend some time manually adding logo pictures for best quality effect and I'm very pleased with the result:
![screen shot 2017-02-08 at 21 14 03](https://cloud.githubusercontent.com/assets/25329994/22755545/e7123d86-ee43-11e6-86a6-d64a7f7d54f5.png)

One thing, when I've disabled and re-enabled the plugin, all links disappeared and I had to start from scratch. What is the way to backup links and custom icons?

**Comment by popcornhax** [comment]
That's the second report of links disappearing, so there is definitely some sort of bug here.  

You can backup the settings/links on the settings page (Gear icon), the images should all be stored in that file.

I would recommend @RoryCombe hold off on publishing to Safari extensions gallery until we can be sure this is fixed.  not sure what's causing it yet.

**Comment by Blazej-pl** [comment]
Held my breath and restarted Safari to be sure, but it's all there after restart. 
Kudos!

**Comment by RoryCombe** [comment]
@dbrowder oops, sorry, already submitted. No possibility to revert now I am afraid. Apple's tools for that are quite limited. I'm not expecting it to be approved quickly though, if I remember correctly last time it was near on 2 months 🙄

**Comment by popcornhax** [comment]
I'm tracking down the bug with losing links on restart, so hopefully I can have a fix that can be submitted before the other one is reviewed/published

As for the links disappearing when you Disable/Enable the extension in settings... yeah, that seems to happen every single time.  For right now I'd suggest not doing that as a workaround.

Sorry for the bugs @RoryCombe - I'm sullying your good name!

**Comment by RoryCombe** [comment]
No problem @dbrowder - it's not that good a name 😂

**Comment by Blazej-pl** [comment]
ver 1.3.1 works, update was smooth and uneventful. You guys rock!
