### ISSUE TITLE
Safari Extensions Gallery installs v1.2

### ISSUE THREAD

**Issue by ckurose** [umfana/FaviconBar#23]
https://safari-extensions.apple.com/details/?id=com.be.faviconbar-FHBT333DVL

**Comment by popcornhax** [comment]
Correct, I don't think this has been published yet.  I recommend holding off on doing so as it seems there is some sort of bug with saving settings, but hopefully that can be sorted out and posted soon.

**Comment by RoryCombe** [comment]
Yes, as @dbrowder says, the new update has been submitted to Apple but is pending their approval before it is published in the gallery

**Comment by RoryCombe** [comment]
The extension has been published in the gallery and should now successfully install the latest version (currently v1.3.2).
