### ISSUE TITLE
Favicon-Does Not Work

### ISSUE THREAD

**Issue by tinkerhell1024** [umfana/FaviconBar#27]
There actually is NO settings "gear" icon, no customizable settings.  Zero options in Safari Extensions window, and no icon in extensions header bar atop webpage to click.

Huge waste of time.

**Comment by Blazej-pl** [comment]
Right click on the Fav bar, make sure you're using latest 1.3.1 
These guys made it for free, works great for me. And you are being kind of an ass right now.

**Comment by popcornhax** [comment]
Hey tinker, sorry to hear this isn't working for you. If you can provide more detail (what version of this bar, where you installed from, version of OS X, version of Safari) I will look into it.

**Comment by popcornhax** [comment]
Closing this issue since we haven't received more information.
