### ISSUE TITLE
Favicon URL address edit is not saved

### ISSUE THREAD

**Issue by Blazej-pl** [umfana/FaviconBar#29]
Hello guys,

Small issue: when I'm doing a right click on favicon from FavBar to edit url address, it's not saved. Right click again gives old url. Editing from main FB settings page works fine. 
I'm using 1.3.1. 
Thanks for awesome work!

**Comment by popcornhax** [comment]
Seems like right-click rename is not working either, how did I screw those up?  I'll get it fixed in the next version.  Thanks for the report.

**Comment by RoryCombe** [comment]
This should now be solved in the latest release. @Blazej-pl: closing this issue for now but feel free to reopen it if its still not working
