### ISSUE TITLE
Detailed settings

### ISSUE THREAD

**Issue by oxydes** [umfana/FaviconBar#30]
Hello,

Where to find the gear icon for detailed settings? I can't see it anywhere. Is it a bug or I miss something. Safari 10.0.2, on 10.11.6

From instructions: 
Detailed settings
Click on the gear icon (⚙) to launch the settings page for more control

Thanks a lot
Kind regards

**Comment by popcornhax** [comment]
Hi Oxydes, did you install the plugin from here on Github (version 1.3.1) or from the Safari Extensions Gallery (version 1.2)?  The extension gallery hasn't been updated yet.

**Comment by oxydes** [comment]
HI! 

Thanks for the reply. I have Safari Ext.Gallery, I have 1.2 version.

OK, so then I better get your most recent copy. :)

Thanks a lot!

**Comment by oxydes** [comment]
Hello again, Now it works perfectly (downloaded from GitHub not Safari Gallery) THANKS!!!
