### ISSUE TITLE
can't insert custom icon

### ISSUE THREAD

**Issue by pamala** [umfana/FaviconBar#37]
I've tried multiple times on identical icons from different sites, to copy over a new icon.  I did click on "change icon" + had the "Choose an icon for ....."  Dragging the image, after searching for an icon, then clicking it didn't work in either in the address or blank space above.  

Not only do I hope that you can help.  But if you can't, I hope there's a way to show the icon name only when the cursor is over it.  Having the names on all icons would take too much room.

THANKS in advance for your help.

**Comment by popcornhax** [comment]
Hi pamala, 
You might have already given up on this - but if you're still out there I'd love to know what version of MacOS and Safari you're using.  Also if you have a link to the icon I will take a look.

As for showing names on mouseover, I'd love to but Apple's extension bar doesn't allow us to see when the mouse hovers over it.  Any mouseover actions just occur when an icon is clicked.

**Comment by pamala** [comment]
OS 10.1206, Safari 10.1.2

Wish I could remember the icon in question.  I’ll be glad to help if I know which 1 it is.

Thanks,
Pamala

**Comment by pamala** [comment]
Rory,

PLEASE help!  All Favicons have disappeared.  Restarting Mac nor uninstalling + reinstalling Favicons works.

I love the app, but REALLY want it to work.

Thanks,
Pamala

**Comment by popcornhax** [comment]
Pamala, did you happen to save settings and links to a file from the settings screen?  That can be used to restore your icons.  I don't know what would have caused this, what version of Safari/MacOS/FaviconBar are you running?

**Comment by pamala** [comment]
Rory,

Safari 10.1.2 + MacOS 10.12.6

I would have saved the settings if I had known how to do it.  But I now can’t even add any icons.  See screenshot:

Thanks,
Pamala

**Comment by popcornhax** [comment]
Sorry Pamala, the pictures didn't come through.  I know this comment is a bit old, but if you still want me to look at this I think you need to login to Github and upload the screenshot - they don't come through email.  -Dan

**Comment by pamala** [comment]
Rory,

Sorry that the screenshot didn’t come through.  I’ve started over again + everything’s fine.  But I’d really like to know how I can save the settings.

Safari 11.0, Favicon Bar 1.3.2, OS 10.13

Thanks,
Pamala

**Comment by popcornhax** [comment]
You can go to the settings page by clicking the gears icon on the bar, and one the settings page the first column is "Save settings and links to a file", click the download button and you can use that to restore your icons if anything goes wrong in the future.  
<img width="498" alt="screen shot 2017-10-08 at 7 45 27 pm" src="https://user-images.githubusercontent.com/6363017/31322650-6432ce76-ac61-11e7-9e06-85fbb205a039.png">

Thanks!

**Comment by pamala** [comment]
Rory,
Thanks so very much for your prompt response.  Now I know where the settings are.  It would be great if there could be an auto-BU.

I tried finding the gear icon, which is normally on the far right.  It was gone.  So I re-started Safari + saw as it opening it appeared momentarily.  Then it disappeared.  The only way to access the settings was to double-click.  This may be a High Sierra issue.

Best regards,
Pamala

**Comment by pamala** [comment]
Rory,

Each time I close Safari or restart, I must re-load my saved settings.  How can this be fixed for OS 10.13 + Safari 11.0?

Thanks,
Pamala

**Comment by popcornhax** [comment]
Pamala, I'm sorry but I can't think of anything that would cause this unless you have some sort of App installed that erases all of your cookies and stored data every time Safari is closed.

**Comment by pamala** [comment]
Rory,

I have an app exactly like that.  But other apps simply allow the user to set the location of BU files.  Then the user can simply BU + restore from the app.  It would be A GREAT idea for Favicon.

Thanks,
Pamala

**Comment by popcornhax** [comment]
Thanks for the suggestion Pamela. As Faviconbar is just a safari extension and not an app the only place we can store data is in Safari’s cache. 

The backup function uses Safari’s download and upload features, but we can’t read other files on the computer. 

Unfortunately I don’t think there is anything we can do about your situation, but it is good to know. Unless there is some way to exclude Faviconbar from your cleanup app it might not be a good option for you. Sorry! 🙁
