### ISSUE TITLE
Allow page title for each favicon

### ISSUE THREAD

**Issue by alucard1990** [umfana/FaviconBar#4]

**Comment by RoryCombe** [comment]
This would be a nice feature. Maybe a first step would be to create a preference for "Show icons only" or "Show icons with text". It's an either-or (set for all or for none) at the moment until I can figure how to allow editing of individual links.

**Comment by popcornhax** [comment]
I realize this is an old request, but I have worked on adding the page-title on each link that can be viewed on right-click, and can be edited in the right-click menu in the next release.  I will soon be adding text label options - these should be ready for the next release.

**Comment by popcornhax** [comment]
This is included in the current release (1.3.1) so I believe this issue can be closed.
