### ISSUE TITLE
Dark Mode for Mojave

### ISSUE THREAD

**Issue by agentmichaelscarn** [umfana/FaviconBar#51]
Will there be a dark mode for FaviconBar so that it blends in with Dark Mode in macOS Mojave?

**Comment by popcornhax** [comment]
Generally faviconbar looks great under Mojave dark mode beta 1.  There are a few known issues, #47 #48 and #52 which will be addressed if Apple doesn't fix them for us in future betas.

As long as you don't have blend into background enabled in settings it looks good on a day-to-day basis right now.
