### ISSUE TITLE
FaviconBar not supported safari 13.0

### ISSUE THREAD

**Issue by milosbz** [umfana/FaviconBar#61]
do you know if any updates are coming to support safari 13.0?

**Comment by popcornhax** [comment]
Unfortunately, no. Apple has removed the ability for an extension like this to exist in Safari 13. Unless they backtrack, this extension will no longer work.

**Comment by chrisyoumans** [comment]
Isn't the new requirement that the extension must be part of an app that is available/installed through their App Store? If so, any idea how big of an undertaking that would be to do?

**Comment by popcornhax** [comment]
That’s correct, but also the new format extensions don’t allow toolbars at all anymore. It’s not part of the new spec, so an App Store app would not work either.

**Comment by milosbz** [comment]
But there must be a way to shrink the bookmarks (in the toolbar) into favicons .. ?

**Comment by popcornhax** [comment]
I knew a guy who was working on overlaying icons into the favorites bar, but it required turning off system integrity protection and was still glitchy. The closest/only thing I know of right now is using emoji for names of favorites.

**Comment by galaxy-nomad** [comment]
> I knew a guy who was working on overlaying icons into the favorites bar, but it required turning off system integrity protection and was still glitchy. The closest/only thing I know of right now is using emoji for names of favorites.

Hi dtb3 I'm looking closely at this option. The only step remaining is to create a custom emoji font that contains all of the images for my bookmarks. I'm looking at Fontlab but still have not figured out how to copy and paste the images in a clean fashion and create a new font. I'll check back in as I progress. If you have any tips on creating a custom emoji font please feel free to share!

**Comment by popcornhax** [comment]
It's been a long time coming, but as of macOS Sonoma 14.4 which will be released shortly, you can now set the Favorites bar to show icons only. 🎉
