### ISSUE TITLE
FaviconBar no longer supported in Safari 13 - send feedback to Apple (link included)

### ISSUE THREAD

**Issue by ej8** [umfana/FaviconBar#62]
This seriously sucks.  How is it that it is 2019 and we can't have icons in the Favorites Bar? WTF. I'm really baffled but had forgotten for years because of FaviconBar.

Send feedback to Apple. Send 10 feedbacks. Send 100.  Here is the link for MacOS Safari feedback:

https://www.apple.com/feedback/safari.html

**Comment by galaxy-nomad** [comment]
I highly recommend moving over to Firefox. You can get identical favicon support by modding UserChrome.css Safari is a lost cause for extensions because Apple pretty much killed all of them. Firefox still supports a myriad of useful extensions without having to download apps from the app store for each one. Here is my Bookmarks bar in Firefox. This is exactly what Safari used to look like with Faviconbar:-) 
<img width="1902" alt="Screen Shot 2019-12-11 at 8 11 07 AM" src="https://user-images.githubusercontent.com/12664589/70638489-d0a69a80-1bed-11ea-8ed0-48a0b2e4d89f.png">

**Comment by Stavrak2** [comment]
The only reason I still use Safari is due to its "Apple-y" nature - passing tabs between Mac and iPhone for example, or the database of passwords I've stored up into it. Other browsers are cool, but the walled garden does have its advantages...

**Comment by galaxy-nomad** [comment]
> The only reason I still use Safari is due to its "Apple-y" nature - passing tabs between Mac and iPhone for example, or the database of passwords I've stored up into it. Other browsers are cool, but the walled garden does have its advantages...

Yeah I recently made the switch back to Safari as it handles passcodes really well in situations where websites ask for two-factor authentication. With Firefox you have to copy and paste codes from an SMS message where Safari now imports those codes from SMS messages automatically:-)

**Comment by Stavrak2** [comment]
^ that's a really good one. That sort of integration, once you get used to it, stops you wanting to leave Apple's domain...

**Comment by galaxy-nomad** [comment]
I agree. Apple REALLY excels at the whole software hardware ecosystem thing especially with their upcoming ARM MacBooks. Also their beautiful aesthetic is matched by no one imho. Not Windows not Android. If you're a visual person which I am I just can't use another system after the beautiful design and integration and workflow offered by Apple. They make mistakes like anyone but they learn from them and usually come back with better products.

**Comment by ademirml** [comment]
Any version compatible with Safari 13 or 14 yet?

**Comment by Stavrak2** [comment]
> Any version compatible with Safari 13 or 14 yet?

What I've been doing is loading up my 'Favourites' section of the bookmarks with the sites I want. Then by clicking on the address bar, you see the icons. 

Otherwise no :p

**Comment by popcornhax** [comment]
Still no way to implement it. I was hoping the new support for chrome extension format would help but that format also does not support toolbars.

**Comment by Gex2501** [comment]
I'm desperate for a favicon toolbar solution in Safari as well. I moved from chrome for all the reasons people mentioned above. Things like this are what make apple frustrating.

**Comment by galaxy-nomad** [comment]
My friend may I highly recommend Brave browser. You get everything you need with favicon bar and on top of that the browser PAYS you crypto currency just to use it. It also had a built in ad blocker so NO YouTube ads/commercials and no ads in web pages and you don't need to install any extra plug-ins to achieve this. Here is a picture of my Bookmarks toolbar with Brave browser:
![Screen](https://user-images.githubusercontent.com/12664589/156098218-b0452e78-b6ec-44a2-b58b-88a1bbcd4d6a.png)

**Comment by popcornhax** [comment]
It's been a long time coming, but as of macOS Sonoma 14.4 which will be released shortly, you can now set the Favorites bar to show icons only. 🎉

**Comment by Stavrak2** [comment]
One thing you can do as a workaround - have a "Favourites Bar" show in safari then either have individual websites or folders of websites in that. To workaround for favicons - rename the sites/folders to use Emoji or Unicode characters.
Any port in a storm...!

I of course await Apple's implementation of Favicons in the bar, but I also expect that they will display randomly (or not at all) with no choice to edit them, so this advice may be useful both before and after 14.4's release.
