### ISSUE TITLE
path to favicon bar url list?

### ISSUE THREAD

**Issue by ACBelkina** [umfana/FaviconBar#63]
I have totally missed the memo that upon Safari upgrade I would be losing my favicon bar. Now I'm on Safari 16.5 and of course it's gone :( I have several full system backups but I would rather not roll the system back because of this. 

Any chance I can go back in Time Machine and look up my list of links for the FaviconBar? I don't have them backed up :( And I could not locate any file in Safari folder that would have them... 

Thanks for your help!

**Comment by RoryCombe** [comment]
Hi @ACBelkina, that is unfortunate. Did you manage to get them back again?
