### ISSUE TITLE
Add License / Clarify Code Usage Guidelines

### ISSUE THREAD

**Issue by afischer** [umfana/FaviconBar#7]
Hey there!

I would love to build off of your codebase, but currently you do not have guidelines in place for forking/creating new extensions/submitting pull requests. It would be fantastic if you could elaborate on how you wish for your source to be credited.

Thanks!

**Comment by RoryCombe** [comment]
Hi @afischer, sorry for the delayed reply, been a bit busy. I'll look into this in the next few days so you can start building.

**Comment by RoryCombe** [comment]
@afischer source and licence file have been added

**Comment by afischer** [comment]
This is fantastic - thanks so much. 
Looking forward to contributing.
