### ISSUE TITLE
Is it possible to have the followings...?

### ISSUE THREAD

**Issue by ShimomiAizo** [umfana/FaviconBar#9]
Hi again and I reached here from apple support forum and here is some little advice to your great extension... Thank you for having developed it!
1. Now the box we have for inputing the addresses is only a single line input box. Can we have a bigger box or a group of input boxes where users can put one address into one box, probably?
2. [totally personal idea] I think things will be even more better when we can have favicon-s and texts working at the same time. For example I would like to have gmail, google calendar and google drive, these three webpages, shown in the bar together, but the problem is favicon-s for the three are all the same. So I have to remember the sequence and to hit the right one I am looking for.
3. [just a wish] Can we change the favicon-s? Manually? For each page?

**Comment by RoryCombe** [comment]
Hi @ShimomiAizo, glad you like the extension and thanks for the suggestions. I'll note them down and see about making some time to implement some of them.

**Comment by popcornhax** [comment]
These suggestions are all included in the current release (1.3.1) so I believe this issue can be closed.
